{
 "title": "Nomad",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "graph",
   "description": "Number of Nomad Jobs that are Running",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_nomad_job_status_running", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Pending",
   "type": "graph",
   "description": "Number of Nomad Jobs that are Pending",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_nomad_job_status_pending", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Dead",
   "type": "graph",
   "description": "Number of Nomad Jobs that are Dead",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_nomad_job_status_dead", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Running",
   "type": "graph",
   "description": "Number of Nomad Jobs that are Running",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_running",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "graph",
   "description": "Number of Nomad Jobs that have Failed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_nomad_job_summary_failed", "legendFormat": "{{exported_job}}" }
   ]
  },
  {
   "title": "Complete",
   "type": "graph",
   "description": "Number of Nomad Jobs that have Completed",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_complete",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Starting",
   "type": "graph",
   "description": "Number of Nomad Jobs that are Starting",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_starting",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Queued",
   "type": "graph",
   "description": "Number of Nomad Jobs that have Queued",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_nomad_job_summary_queued", "legendFormat": "{{exported_job}}" }
   ]
  },
  {
   "title": "Lost",
   "type": "graph",
   "description": "Number of Nomad Jobs that are Lost",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_nomad_job_summary_lost", "legendFormat": "{{exported_job}}" }
   ]
  },
  { "title": "Allocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Allocations/s",
   "type": "graph",
   "description": "Number of Nomad Allocations",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nomad_nomad_client_allocations_stats_count[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}